<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="乐乘" duration-ms="31232" started-at="2016-12-06T07:58:49Z" finished-at="2016-12-06T07:59:20Z">
    <groups>
      <group name="login">
        <method signature="TheLoginTest.toLoginTest(java.util.Map)[pri:0, instance:test.lecheng.login.TheLoginTest[name=InstrumentDriverTestCase,maxpri=10]]" name="toLoginTest" class="test.lecheng.login.TheLoginTest"/>
      </group> <!-- login -->
    </groups>
    <test name="乐乘｜登陆" duration-ms="31232" started-at="2016-12-06T07:58:49Z" finished-at="2016-12-06T07:59:20Z">
      <class name="test.lecheng.login.TheLoginTest">
        <test-method status="PASS" signature="prepareResource()[pri:0, instance:test.lecheng.login.TheLoginTest[name=InstrumentDriverTestCase,maxpri=10]]" name="prepareResource" is-config="true" duration-ms="1071" started-at="2016-12-06T15:58:48Z" finished-at="2016-12-06T15:58:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prepareResource -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:test.lecheng.login.TheLoginTest[name=InstrumentDriverTestCase,maxpri=10]]" name="setUp" is-config="true" duration-ms="92" started-at="2016-12-06T15:58:49Z" finished-at="2016-12-06T15:58:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="toLoginTest(java.util.Map)[pri:0, instance:test.lecheng.login.TheLoginTest[name=InstrumentDriverTestCase,maxpri=10]]" name="toLoginTest" duration-ms="27697" started-at="2016-12-06T15:58:49Z" data-provider="dp" finished-at="2016-12-06T15:59:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{实际输出=［测试脚本]出现异常，案例执行失败！java.lang.ArrayIndexOutOfBoundsException: 3, 测试结果=FAIL, 案例编号=自动化案例-001, 姓名=, 预期输出=登陆后，正常退出, 用户名=1000000, 类名=test.lecheng.login.TheLoginTest, 方法名=toLoginTest, 输入项=[姓名=,案例编号=自动化案例-001,用户名=1000000,预期输出=登陆后，正常退出,案例编写人=jinde,账户=账户5,密码=123456,导航栏名称=首页|乐乘|登录,], 密码=123456, 导航栏名称=首页|乐乘|登录, 案例编写人=jinde, 账户=账户5, 测试时间=2016-12-06 15:58:49}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.ArrayIndexOutOfBoundsException">
            <message>
              <![CDATA[3]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 3
	at carsmart.lecheng.login.Login.toLogin(Login.java:35)
	at test.lecheng.login.TheLoginTest.toLoginTest(TheLoginTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:74)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArrayIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- toLoginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.lecheng.login.TheLoginTest[name=InstrumentDriverTestCase,maxpri=10]]" name="tearDown" is-config="true" duration-ms="3082" started-at="2016-12-06T15:59:17Z" finished-at="2016-12-06T15:59:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="aftersuite()[pri:0, instance:test.lecheng.login.TheLoginTest[name=InstrumentDriverTestCase,maxpri=10]]" name="aftersuite" is-config="true" duration-ms="2" started-at="2016-12-06T15:59:21Z" finished-at="2016-12-06T15:59:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftersuite -->
      </class> <!-- test.lecheng.login.TheLoginTest -->
    </test> <!-- 乐乘｜登陆 -->
  </suite> <!-- 乐乘 -->
</testng-results>
